setwd("C:/Users/priya/OneDrive/Documents/coding/5th semister/AL/Class 7") 
library("xlsx")
data1=read.xlsx("StudentNA.xlsx",sheetIndex=1) 
data2=read.xlsx("StudentNA.xlsx",sheetIndex=2) 
cat("\nData before omitting NA values:\n") 
data=merge(data1,data2)
print(data)
cat("\nData after omitting NA values:\n") 
data=na.omit(data)
print(data)
write.xlsx(data, file="C:/Users/priya/OneDrive/Documents/coding/5th semister/AL/Class 7/Student_wout_NA.xlsx", sheetName="Without NA Values")
cat("New Excel file created.")
