install.packages("xlsx")
setwd("C:/Users/priya/OneDrive/Documents/coding/5th semister/AL/Class 7") 
library("xlsx")
cat("\nSheet 1:\n") 
data1=read.xlsx("Student.xlsx", sheetIndex = 1) 
print(data1)
cat("\nSheet 2:\n") 
data2=read.xlsx("Student.xlsx", sheetIndex = 2) 
print(data2)
